runs:
  using: "composite"
  steps: 
    - uses: hadolint/hadolint-action@v2.0.0
      with:
        dockerfile: Dockerfile
    - name: Build the Docker image
      shell: bash
      run: docker build .
