name: CI Verify Cloudformation

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.cloudformation.yml"
jobs:
  verify-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint *.cloudformation.yml
